Repository CIT-NakamuraLab/project-alpha-cs, pull requests merged in 2022-12, with the labels that each got.

#1 Slack OAuthの対応
  .eslintignore
  .gitignore
  certificates/.gitkeep
  package.json
  prisma/schema.prisma
  sslServer.js
  tsconfig.json
Labels: feature / 機能追加, backend / バックエンド

#6 #3-1 DB用のスキーマファイルを定義
  prisma/schema.prisma
Labels: feature / 機能追加, backend / バックエンド

#7 #3-1 datetimeのカラム型が正しくなかった問題を修正
  prisma/schema.prisma
Labels: bug / バグ, backend / バックエンド

#9 CIにPrisma Schemaのバリデーションを追加
  .github/workflows/prisma-schema.yml
  .gitignore
  package.json
  prisma/schema.prisma
Labels: bug / バグ, feature / 機能追加, backend / バックエンド

#10 DBのデータが虚無に消える問題を修正
  .gitignore
  docker-compose.yml
Labels: bug / バグ, backend / バックエンド

#13 リーダー用のtRPCの実装
  prisma/schema.prisma
  src/server/trpc/router/reader.ts
  src/utils/client.ts
Labels: feature / 機能追加, backend / バックエンド

#12 UIのベースデザインを追加
  package.json
  src/components/ReaderBody.tsx
  src/components/SettingMenu.tsx
  src/pages/index.tsx
  src/pages/log.tsx
  src/pages/login.tsx
  src/pages/settings/profile.tsx
  src/pages/settings/reader.tsx
  src/pages/settings/user.tsx
  yarn.lock
Labels: feature / 機能追加, frontend / フロントエンド

#11 開発に関するドキュメントの追加
  .env.example
  README.md
  docs/architecture.md
  docs/assets/arch-v0.drawio
  docs/assets/arch-v0.svg
  docs/assets/flow-v0.drawio
  docs/assets/flow-v0.svg
  docs/flow.md
Labels: documentation / ドキュメント, backend / バックエンド, frontend / フロントエンド

#16 一部環境にてprettierでディレクトリの再帰的探索が行われないバグを修正
  package.json
Labels: bug / バグ

#17 ユーザ用のtRPCを追加
  src/server/trpc/router/user.ts
Labels: feature / 機能追加, backend / バックエンド

#19 Admin用のprocedureの実装
  src/server/trpc/router/reader.ts
  src/server/trpc/router/user.ts
  src/server/trpc/trpc.ts
Labels: feature / 機能追加, backend / バックエンド

#21 Build用のCIのエラーを修正
  .github/workflows/build-test.yml
Labels: bug / バグ

#22 Admin用procedureが正しく認証していなかった不具合を修正
  src/server/trpc/trpc.ts
Labels: bug / バグ, backend / バックエンド

#24 tRPCの実装の修正・改善
  src/server/trpc/router/_app.ts
  src/server/trpc/router/example.ts
  src/server/trpc/router/reader.ts
  src/server/trpc/router/user.ts
  src/server/trpc/trpc.ts
Labels: bug / バグ, backend / バックエンド

#28 ユーザ用tRPCの追加
  src/server/trpc/router/user.ts
Labels: feature / 機能追加, backend / バックエンド

#25 tRPCのLog周りの実装を追加
  src/server/trpc/router/_app.ts
  src/server/trpc/router/log.ts
Labels: feature / 機能追加, backend / バックエンド

#27 学生番号登録・確認用のロジックを実装
  .env.example
  node-env.d.ts
  package.json
  src/pages/api/auth/google.ts
  src/pages/api/auth/url.ts
  src/utils/google.ts
  yarn.lock
Labels: feature / 機能追加, backend / バックエンド, frontend / フロントエンド

#31 サインイン画面およびメイン画面の作成
  package.json
  public/images/dsc_0298.jpeg
  public/images/dsc_0299.jpeg
  src/components/GeneralButton.tsx
  src/components/SettingMenu.tsx
  src/components/UserBody.tsx
  src/components/homeContents/Contents.tsx
  src/components/homeContents/KeyImage.tsx
  src/components/homeContents/MemberCount.tsx
  src/components/homeContents/Pickup.tsx
  src/components/layout/Layout.tsx
  src/pages/index.tsx
  src/pages/log.tsx
  src/pages/settings/profile.tsx
  src/pages/settings/user.tsx
  yarn.lock
Labels: feature / 機能追加, frontend / フロントエンド
