Repository CIT-NakamuraLab/project-alpha-cs, pull requests merged in 2023-03, with the labels that each got.

#40 学籍番号や鍵の有無から画面を切り替える処理の実装
  src/components/homeContents/Contents.tsx
  src/components/homeContents/KeyImage.tsx
  src/components/homeContents/MemberCount.tsx
  src/components/homeContents/Pickup.tsx
  src/pages/googleAuthResult.tsx
  src/pages/index.tsx
Labels: feature / 機能追加, frontend / フロントエンド

#43 工大アカウントで認証した後のルーティングを実装
  src/pages/api/auth/google.ts
Labels: frontend / フロントエンド

#42 リーダー管理画面の実装
  package.json
  src/components/GeneralDivider.tsx
  src/components/ReaderBody.tsx
  src/components/ReaderCard.tsx
  src/components/SettingMenu.tsx
  yarn.lock
Labels: feature / 機能追加, frontend / フロントエンド

#44 カスタムサーバの設定を一部変更
  sslServer.js
Labels: backend / バックエンド, frontend / フロントエンド

#45 ページに認証を実装
  src/components/SettingMenu.tsx
  src/pages/log.tsx
  src/pages/settings/profile.tsx
  src/pages/settings/reader.tsx
  src/pages/settings/user.tsx
Labels: frontend / フロントエンド
