Repository CIT-NakamuraLab/project-alpha-cs, pull requests merged in 2023-02, with the labels that each got.

#33 Google認証の処理の結果出力画面の実装
  public/images/badmark.png
  public/images/checkmark.png
  src/components/homeContents/Contents.tsx
  src/pages/googleAuthResult.tsx
  src/pages/index.tsx
Labels: feature / 機能追加, frontend / フロントエンド

#36 現在の入室している人の名前を取得するtrpcQueryを実装
  src/server/trpc/router/log.ts
Labels: feature / 機能追加, backend / バックエンド

#34 リーダーから受け取るログ追加用RESTAPIエンドポイントを追加
  prisma/schema.prisma
  src/pages/api/logs.ts
Labels: feature / 機能追加, backend / バックエンド

#37 fix: trpc getActiveUsers query
  src/server/trpc/router/log.ts
Labels: bug / バグ, backend / バックエンド

#38 LogTypeを定数化
  src/server/trpc/router/log.ts
  src/utils/const.ts
Labels: backend / バックエンド, frontend / フロントエンド

#39 鍵を取りに行く場合のログ生成・削除処理を追加
  src/pages/api/logs.ts
  src/server/trpc/router/log.ts
Labels: backend / バックエンド
